### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by amirouche** [amirouche/sensimark#3]
- [ ] use http://benalexkeen.com/feature-scaling-with-scikit-learn/
- [ ] do not compute the mean for super categories but the sum of subcategories
- [x] use stop words
- [x] stemming
- [x] level 5m, see #4

**Comment by amirouche** [comment]
https://github.com/wolfgarbe/symspell
